set(MODEM_REVISIONS "AB" "AD")
if (NOT DEFINED BOARD_REVISION)
  set(BOARD_REVISION "AD")
else()
  if (NOT BOARD_REVISION IN_LIST MODEM_REVISIONS)
    message(FATAL_ERROR "${BOARD_REVISION} is not a valid revision for Gen5 modem. Accepted revisions: ${MODEM_REVISIONS}")
  endif()
endif()
