set(AGGB_REVISIONS "AC")
if (NOT DEFINED BOARD_REVISION)
  set(BOARD_REVISION "AC")
else()
  if (NOT BOARD_REVISION IN_LIST AGGB_REVISIONS)
    message(FATAL_ERROR "${BOARD_REVISION} is not a valid revision for Gen5 Dev board. Accepted revisions: ${AGGB_REVISIONS}")
  endif()
endif()
