/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright (C) 2023 SLB
 *
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_INFINEON_XMC4XXX_CLOCKS_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_INFINEON_XMC4XXX_CLOCKS_H_

#define XMC4XXX_EXT_CLOCK 0

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_INFINEON_XMC4XXX_CLOCKS_H_ */
